apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: spanner.googleapis.com
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerInstance
metadata:
  name: spannerinstance-1 # kpt-set: ${name}
  namespace: config-control # kpt-set: ${namespace}
  labels:
    environment: kasna
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  config: regional-us-west1
  displayName: Spanner Instance Sample
  numNodes: 2
