apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: spanner.googleapis.com
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/kasna-test-landingzone # kpt-set: projects/${management-project-id}
---
apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerDatabase
metadata:
  name: spanner-sample-database # kpt-set: ${database-name}
  namespace: projects-namespace # kpt-set: ${projects-namespace}
spec:
  ddl:
    - "CREATE TABLE t1 (t1 INT64 NOT NULL,) PRIMARY KEY(t1)"
  instanceRef:
    name: spanner-sample-instance # kpt-set: ${instance-name}
---
apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerInstance
metadata:
  name: spanner-sample-instance # kpt-set: ${instance-name}
  namespace: projects # kpt-set: ${projects-namespace}
spec:
  config: regional-us-central1 # kpt-set: ${config-region}
  displayName: "spanner-sample-instance" # kpt-set: ${instance-name}
  numNodes: 1 # kpt-set: ${num-nodes}
