apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: sqladmin.googleapis.com
  namespace: config-controller-system # {"$kpt-set":"namespace"}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: sqldatabase-10
  namespace: config-controller-system # {"$kpt-set":"namespace"}
spec:
  region: us-central1
  databaseVersion: MYSQL_5_7
  settings:
    tier: db-n1-standard-1