# Grant KCC owner of this project
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: kcc-project-name-owners-permissions # kpt-set: kcc-${project-name}-owners-permissions
  namespace: project-name # kpt-set: ${project-name}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/kcc-namespace/v0.3.0
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  bindings:
    - members:
        - member: serviceAccount:project-name-sa@management-project-id.iam.gserviceaccount.com # kpt-set: serviceAccount:${project-name}-sa@${management-project-id}.iam.gserviceaccount.com
      role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: project-id # kpt-set: ${project-id}
