apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: project-name-gke # kpt-set: ${project-name}-gke-cluster
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
    cnrm.cloud.google.com/remove-default-node-pool: "false"
spec:
  description: A routes-based cluster confined to one zone configured for development.
  location: location # kpt-set: ${location}
  initialNodeCount: 1
  clusterTelemetry:
    type: SYSTEM_ONLY
  networkingMode: VPC_NATIVE
  networkRef:
    name: project-name-network # kpt-set: ${project-name}-network
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  subnetworkRef:
    name: project-name-subnetwork # kpt-set: ${project-name}-primary-subnet
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  ipAllocationPolicy:
    clusterSecondaryRangeName: project-name-subnetwork # kpt-set: ${project-name}-cluster-subnet
    servicesSecondaryRangeName: project-name-subnetwork # kpt-set: ${project-name}-services-subnet
  masterAuthorizedNetworksConfig:
    cidrBlocks:
      - displayName: project-name-network # kpt-set: ${project-name}-network
        cidrBlock: 10.2.0.0/16
  enableIntranodeVisibility: true
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: 00:00
  workloadIdentityConfig:
      identityNamespace: project-id.svc.id.goog # ${project-id}.svc.id.goog
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    networkPolicyConfig:
      disabled: false
    networkPolicy:
      enabled: true
    dnsCacheConfig:
      enabled: true
    configConnectorConfig:
      enabled: true
    podSecurityPolicyConfig:
      enabled: true
    verticalPodAutoscaling:
      enabled: true