apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: project-name-network # kpt-set: ${project-name}-network
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: project-name-subnetwork # kpt-set: ${project-name}-subnetwork
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  description: description # kpt-set: ${project-name}-subnetwork
  privateIpGoogleAccess: true
  networkRef:
    name: project-name-network # kpt-set: ${project-name}-network
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA