apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: compute-network-name # kpt-set: ${compute-network-name}
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: compute-network-name-subnetwork # kpt-set: ${compute-network-name}-subnetwork
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  description: My subnet
  privateIpGoogleAccess: true
  networkRef:
    name: compute-network-name # kpt-set: ${compute-network-name}
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA