apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: project-name-subscription # kpt-set: ${project-name}-subscription
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  messageRetentionDuration: 3600s
  retainAckedMessages: false
  topicRef:
    external: pubsub-topic # kpt-set: ${pubsub-topic}