# Create a Service Account to scope RBAC for namespace
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: project-id-sa # kpt-set: ${project-id}-sa
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone/v0.2.0
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  displayName: project-name-sa # kpt-set: ${project-name}-sa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: project-idname-admin # kpt-set: ${project-id}-admin
  namespace: projects-namespace # kpt-set: ${projects-namespace}
spec:
  member: user:juelian.siow@test.kasna.com.au
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    namespace: projects-namespace # kpt-set: ${projects-namespace}
    kind: Project
    name: project-id # kpt-set: ${project-id}