apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
data:
  management-project-id: kasna-test-landingzone
  projects-namespace: telstra
  project-name: telstra-team1
  project-id: team1-kl398gfnso
  billing-account-id: 014244-F1A39A-218EB5
  location: us-central1
  folder-id: 183622773365