apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: compute-network-name # kpt-set: ${compute-network-name}
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: compute-network-name-subnetwork # kpt-set: ${compute-network-name}-subnetwork
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  ipCidrRange: 10.2.0.0/16
  region: us-central1
  description: My subnet
  privateIpGoogleAccess: true
  networkRef:
    name: compute-network-name # kpt-set: ${compute-network-name}
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  logConfig:
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
    metadata: INCLUDE_ALL_METADATA
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: compute-network-name-firewall # kpt-set: ${compute-network-name}-firewall
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  deny:
    - protocol: tcp
    - protocol: icmp
  direction: INGRESS
  networkRef:
    name: compute-network-name # kpt-set: ${compute-network-name}
    namespace: projects-namespace # kpt-set: ${projects-namespace}
priority: 5000
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: container.googleapis.com
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/management-project-id # kpt-set: projects/${management-project-id}
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: container-cluster-name-gke-cluster # kpt-set: ${container-cluster-name}-gke-cluster
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
    cnrm.cloud.google.com/remove-default-node-pool: "false"
spec:
  description: A routes-based cluster confined to one zone configured for development.
  location: us-central1
  initialNodeCount: 1
  clusterTelemetry:
    type: SYSTEM_ONLY
  networkingMode: ROUTES
  clusterIpv4Cidr: 10.96.0.0/14
  masterAuthorizedNetworksConfig:
    cidrBlocks:
      - displayName: Trusted external network
        cidrBlock: 10.2.0.0/16
  addonsConfig:
    gcePersistentDiskCsiDriverConfig:
      enabled: true
    kalmConfig:
      enabled: true
    horizontalPodAutoscaling:
      disabled: true
    httpLoadBalancing:
      disabled: true
  networkRef:
    name: compute-network-name # kpt-set: ${compute-network-name}
    namespace: projects-namespace # kpt-set: ${projects-namespace}
  subnetworkRef:
    name: compute-network-name-subnetwork # kpt-set: ${compute-network-name}-subnetwork
    namespace: projects-namespace # kpt-set: ${projects-namespace}
---
