apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: computeinstance-sample-backend
  labels:
    created-from: "image"
    network-type: "subnetwork"
spec:
  machineType: f1-micro
  zone: us-central1-a
  bootDisk:
    initializeParams:
      size: 24
      type: pd-ssd
      sourceImageRef:
        external: debian-cloud/debian-9
  networkInterface:
    - subnetworkRef:
        name: computeinstance-backend # {"$kpt-set":"subnet"}
  minCpuPlatform: "Intel Skylake"
  metadataStartupScript: "apt update\n
                          apt -y upgrade\n
                          apt -y install apache2\n"
