apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per Namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: project-name # kpt-set: ${project-name}
spec:
  # The Google Service Account used to authenticate Google Cloud APIs in this Namespace
  # Convention name based
  googleServiceAccount: "cnrm-system-project-name@kasna-test-landingzone.iam.gserviceaccount.com" # kpt-set: cnrm-system-${project-name}@${management_project_id}.iam.gserviceaccount.com
