# Create namespace in the Kubernetes cluster to manage KCC resources in this project
apiVersion: v1
kind: Namespace
metadata:
  name: project-name # kpt-set: ${project-name}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: project-name-projectcreator-permissions # kpt-set: ${project-name}-projectcreator-permissions
  namespace: config-control # kpt-set: ${management-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone/v0.2.0
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  member: "serviceAccount:project-name-sa@management-project-id.iam.gserviceaccount.com" # kpt-set: serviceAccount:${project-name}-sa@${management-project-id}.iam.gserviceaccount.com
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: project-name  # kpt-set: ${project-name}
  role: roles/owner
---
# Allow KCC's Kubernetes Service Account to use the GCP ServiceAccount
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: project-name-sa-workload-identity-binding # kpt-set: ${project-name}-sa-workload-identity-binding
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  resourceRef:
    external: projects/kasna-test-landingzone/serviceAccounts/service-account # kpt-set: projects/kasna-test-landingzone/serviceAccounts/${project-name}-sa@${management-project-id}.iam.gserviceaccount.com
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:management-project-id.svc.id.goog[config-management-system/ns-reconciler-project-name] # kpt-set: serviceAccount:${management-project-id}.svc.id.goog[config-management-system/ns-reconciler-${project-name}]