apiVersion: rbac.authorization.k8s.io/v1
# sync-rolebinding.yaml
kind: RoleBinding
metadata:
  name: sync-repo # kpt-set: sync-repo-${project-name}
  namespace: projects # kpt-set: ${projects-namespace}
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-project-name # kpt-set: ns-reconciler-${project-name}
    namespace: config-management-system