apiVersion: rbac.authorization.k8s.io/v1
# sync-rolebinding.yaml
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: project-id # kpt-set: ${project-id}
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: ns-reconciler-dbteam-1 # kpt-set: ns-reconciler-${project-id}
    namespace: config-management-system
    kind: ServiceAccount
