apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-repo # kpt-set: sync-repo-${project-id}
  namespace: projects # kpt-set: ${project-name}
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-project-id # kpt-set: cnrm-controller-manager-${project-id}
    kind: ServiceAccount
    namespace: cnrm-system