apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-repo # kpt-set: sync-repo-${project-name}
  namespace: projects # kpt-set: ${project-name}
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: project-name # kpt-set: ${project-name}
    namespace: config-management-system