apiVersion: rbac.authorization.k8s.io/v1
# sync-rolebinding.yaml
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: projects # kpt-set: ${projects-namespace}
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ns-reconciler-project-name # kpt-set: ns-reconciler-${project-name}
    namespace: config-management-system
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: 915663602069-compute@developer.gserviceaccount.com