apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-name-ksa # kpt-set: ${project-name}-ksa
  annotations:
    iam.gke.io/gcp-service-account: cnrm-system-project-name@kasna-test-landingzone.iam.gserviceaccount.com # kpt-set: cnrm-system-${project-name}@${management-project-id}.iam.gserviceaccount.com
