apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: logging.googleapis.com 
  namespace: config-controller-system # {"$kpt-set":"namespace"}
---
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: logginglogsink-sample-project
  namespace: config-controller-system # {"$kpt-set":"namespace"}
spec:
  projectRef:
    name: kasna-test-landingzone
  uniqueWriterIdentity: true
  destination:
    pubSubTopicRef:
      name: kasna-test-landingzone
  filter: resource.type="bigquery_project" AND logName:"cloudaudit.googleapis.com"
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: logginglogsink-dep-project
  namespace: config-controller-system # {"$kpt-set":"namespace"}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
    cnrm.cloud.google.com/organization-id: "923715671876"
  name: logginglogsink-dep-project
  namespace: config-controller-system # {"$kpt-set":"namespace"}
spec:
  name: Project Sink Sample
  billingAccountRef:
    external: 014244-F1A39A-218EB5