apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: telstra-team1-dns # kpt-set: ${project-name}-dns
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  description: "telstra-team1-DNS-zone" # kpt-set: ${project-name}-DNS-zone
  dnsName: "telstra-team1-telstra-innovation.com." # kpt-set: ${project-name}-telstra-innovation.com.
  privateVisibilityConfig:
    networks:
      - networkRef:
          name: telstra-team1-network # kpt-set: ${project-name}-network
          namespace: projects # kpt-set: ${projects-namespace}
  visibility: private
