apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: telstra-team1-fw # kpt-set: ${project-name}-fw
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  priority: 5000
  deny:
    - protocol: tcp
    - protocol: icmp
  direction: INGRESS
  networkRef:
    name: telstra-team1-network # kpt-set: ${project-name}-network
    namespace: projects # kpt-set: ${projects-namespace}
