apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: telstra-team1-network # kpt-set: ${project-name}-network
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: telstra-team1-primary-subnet # kpt-set: ${project-name}-primary-subnet
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  description: telstra-team1-subnetwork # kpt-set: ${project-name}-subnetwork
  ipCidrRange: 10.2.0.0/16
  logConfig:
    metadata: INCLUDE_ALL_METADATA
    aggregationInterval: INTERVAL_10_MIN
    flowSampling: 0.5
  networkRef:
    name: telstra-team1-network # kpt-set: ${project-name}-network
    namespace: projects # kpt-set: ${projects-namespace}
  privateIpGoogleAccess: true
  region: australia-southeast1 # kpt-set: ${location}
  secondaryIpRange:
    - ipCidrRange: 10.3.0.0/16
      rangeName: telstra-team1-services-subnet # kpt-set: ${project-name}-services-subnet
    - ipCidrRange: 10.4.0.0/16
      rangeName: telstra-team1-cluster-subnet # kpt-set: ${project-name}-cluster-subnet
