apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: telstra-team1-subscription # kpt-set: ${project-name}-subscription
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  messageRetentionDuration: 3600s
  retainAckedMessages: false
  topicRef:
    external: projects/telstra-innova-ops-4jydfe/topics/telstra-innova-ops-pubsub # kpt-set: ${pubsub-topic}
