# Create a Service Account to scope RBAC for namespace
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: team1-83etc-sa # kpt-set: ${project-id}-sa
  namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone/v0.2.0
    cnrm.cloud.google.com/project-id: team1-83etc # kpt-set: ${project-id}
spec:
  displayName: telstra-team1-sa # kpt-set: ${project-name}-sa
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: team1-83etc-admin # kpt-set: ${project-id}-admin
  namespace: projects # kpt-set: ${projects-namespace}
spec:
  member: "group:telstra-admin@kasna.cloud"
  resourceRef:
    name: team1-83etc # kpt-set: ${project-id}
    namespace: projects # kpt-set: ${projects-namespace}
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
  role: roles/editor
