apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: monitoring.googleapis.com
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringGroup
metadata:
  name: monitoringgroup-sample # kpt-set: ${platform-project-id}-${name}
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  displayName: "MonitoringSubGroup"
  filter: resource.metadata.name=has_substring("test")
  parentRef:
    name: monitoringgroup-dep
---
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringGroup
metadata:
  name: monitoringgroup-dep
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  displayName: "MonitoringGroup"
  filter: resource.metadata.region=europe-west2
