apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: computeinstance-dep-cloudmachine
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${management-project-id}
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: computeinstance-dep-cloudmachine
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  ipCidrRange: 10.2.0.0/16
  networkRef:
    name: computeinstance-dep-cloudmachine
  region: us-central1
  secondaryIpRange:
    - ipCidrRange: 10.3.16.0/20
      rangeName: cloudrange
