apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # Unique across all clusters using the same ConfigSync repo. Name is used in Cluster Selectors
  clusterName: config-controller-1 # kpt-set: ${cluster-name}
  enableMultiRepo: true
