apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtabletableadmin.googleapis.com
  namespace: projects # kpt-set: ${management-namespace}
spec:
  projectRef:
    external: projects/kasna-test-landingzone
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtableadmin.googleapis.com
  namespace: config-control # kpt-set: ${management-namespace}
spec:
  projectRef:
    external: projects/kasna-test-landingzone
---
kubectl apply -f - <<EOF
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: blueprints-project-bigtableinstance # kpt-set: ${name}
  annotations:
    cnrm.cloud.google.com/project-id: kasna-test-landingzone
spec:
  displayName: BigtableS1
  cluster:
  - clusterId: bigtableinstance1
    zone: us-central1-a
    numNodes: 3
  - clusterId: bigtableinstance2
    zone: us-west1-a
    numNodes: 3
EOF