apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtabletableadmin.googleapis.com
  namespace: config-control
spec:
  projectRef:
    external: projects/kasna-test-landingzone
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtableadmin.googleapis.com
  namespace: config-control
spec:
  projectRef:
    external: projects/kasna-test-landingzone
---
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: blueprints-uniquekasna # kpt-set: ${name}
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: kasna-test-landingzone
spec:
  displayName: bigtable-1
  cluster:
  - clusterId: bigtableuniqqsa
    zone: us-central1-a
    numNodes: 3
  - clusterId: bigtableuniqqsa
    zone: us-west1-a
    numNodes: 3