apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtabletableadmin.googleapis.com
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bigtableadmin.googleapis.com
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: bigtableinstance-1 # kpt-set: ${name}
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  cluster:
    - clusterId: bigtableinstance-dep1
      numNodes: 3
      zone: us-central1-a
    - clusterId: bigtableinstance-dep2
      numNodes: 3
      zone: us-west1-a
  displayName: BigtableSample
