# Give CNRM for this project's namespace permission to read CNRM resources in the projects namespace.
# This allows IAMMemberPolicy in this project's namespace to reference the project in the projects namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnrm-project-viewer-project-id # kpt-set: cnrm-project-viewer-${project-id}
  namespace: projects # kpt-set: ${projects-namespace}
roleRef:
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-project-id # kpt-set: cnrm-controller-manager-${project-id}
    namespace: cnrm-system
    kind: ServiceAccount