apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: project-id # kpt-set: ${project-id}
  namespace: projects # kpt-set: ${project-namespace}
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
    cnrm.cloud.google.com/project-id: kasna-test-landingzone # kpt-set: ${management-project-id}
    cnrm.cloud.google.com/folder-id: "174187959254"
    config.kubernetes.io/function: |
      container:
        image: gcr.io/yakima-eap/folder-ref:latest
spec:
  name: project-id # kpt-set: ${project-id}
  billingAccountRef:
    external: "AAAAAA-BBBBBB-CCCCCC" # kpt-set: ${billing-account-id}