apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: project-name # kpt-set: ${project-id}
  namespace: projects
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
    cnrm.cloud.google.com/project-id: kasna-test-landingzone
spec:
  name: project-name # kpt-set: ${project-id}
  folderRef:
    external: "824343073954"
  billingAccountRef:
    external: "014244-F1A39A-218EB5"
