apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRoute
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: computeroute-sample  # {"$kpt-set":"name"}
  namespace: config-control
spec:
  description: "A sample compute route"
  destRange: 192.168.1.0/24 # {"$kpt-set":"destRange"}
  networkRef:
    name: computeroute-dep
  priority: 1000 # {"$kpt-set":"priority"}
  nextHopIp: 10.132.1.5 # {"$kpt-set":"nextHopIp"}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
    cnrm.cloud.google.com/deletion-policy: "abandon"
  name: computeroute-dep  
  namespace: config-control
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: true
  description: Default network for the project
