apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRoute
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: computeroute-sample  # {"$kpt-set":"route-name"}
  namespace: config-control
spec:
  description: "A sample compute route"
  destRange: 192.168.1.0/24 # {"$kpt-set":"destRange"}
  networkRef:
    name: computeroute-dep # {"$kpt-set":"network"}
  priority: 1000 # {"$kpt-set":"priority"}
  nextHopIp: 10.132.1.5 # {"$kpt-set":"nextHopIp"}