apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
    cnrm.cloud.google.com/deletion-policy: "abandon"
  name: computeroute-dep # {"$kpt-set":"network"}
  namespace: config-control
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: true
  description: Default network for the project