apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: dev.ops
  namespace: hierarchy # kpt-set: ${hierarchy-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:hierarchy:env-bu/v0.2.0
spec:
  displayName: ops
  folderRef:
    name: dev
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  name: prod.ops
  namespace: hierarchy # kpt-set: ${hierarchy-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:hierarchy/v0.1.1
spec:
  displayName: ops
  folderRef:
    name: prod
