apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  name: iamcustomroletelstra
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: kasna-test-landingzone # kpt-set: ${management-project-id}
spec:
  description: Telstra SQL Viewer
  permissions:
    - cloudsql.instances.get
    - cloudsql.instances.list
  stage: GA
  title: Custom Role - CloudSQL Viewer
