apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  name: iamcustomrolecloudsqlviewer
  namespace: config-controller-system
  annotations:
    cnrm.cloud.google.com/project-id: kasna-test-landingzone # kpt-set: ${project-id}
spec:
  description: CloudSQL Viewer
  permissions:
    - cloudsql.instances.get
    - cloudsql.instances.list
  stage: GA
  title: Custom Role - CloudSQL Viewer
