apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: service-account-name # kpt-set: ${service-account-name}
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  displayName: service-account-name # kpt-set: ${service-account-name}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-kcc
  namespace: config-control
spec:
  member: user:sam.gh.lin@gmail.com # kpt-set: ${iam-member}
  resourceRef:
    name: service-account-name # kpt-set: ${service-account-name}
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  role: roles/iam.serviceAccountKeyAdmin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: telstra-iam-sa
  namespace: config-control
spec:
  member: "serviceAccount:service-account-name@management-project-id.iam.gserviceaccount.com" # kpt-set: serviceAccount:${service-account-name}@${management-project-id}.iam.gserviceaccount.com
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kasna-test-landingzone # kpt-set: projects/${management-project-id}
  role: roles/owner