apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: service-account-cloudsql # kpt-set: ${service-account-name}
  namespace: config-controller-system
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-service-account
  namespace: config-controller-system
spec:
  member: user:sam.gh.lin@gmail.com # kpt-set: ${iam-member}
  resourceRef:
    name: service-account-cloudsql # kpt-set: ${service-account-name}
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  role: roles/iam.serviceAccountKeyAdmin
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: project-iam-sa
  namespace: config-controller-system
spec:
  member: serviceAccount:service-account-cloudsql@kasna-test-landingzone.iam.gserviceaccount.com # kpt-set: serviceAccount:${service-account-name}@${project-id}.iam.gserviceaccount.com
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kasna-test-landingzone # kpt-set: projects/${project-id}
  role: roles/cloudsql.admin # kpt-set: ${role}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: project-iam-member
  namespace: config-controller-system
spec:
  member: user:sam.gh.lin@gmail.com # kpt-set: ${iam-member}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/kasna-test-landingzone # kpt-set: projects/${project-id}
  role: roles/cloudsql.admin # kpt-set: ${role}
