apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: bqadmin
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.2.0
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.scom/disable-dependent-services: "false"
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  resourceID: bigquery.googleapis.com
---
# Folder Sink to BQ
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: my.folder.k8s.name-bqsink # kpt-set: ${log-folder-name}-bqsink
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.2.0
spec:
  destination:
    bigQueryDatasetRef:
      name: bqlogexportdataset
  filter: "" # kpt-set: ${filter}
  folderRef:
    name: my.folder.k8s.name # kpt-set: ${log-folder-name}
  includeChildren: true
---
# BQ Dataset
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bqlogexportdataset
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/blueprint: cnrm/landing-zone:log-export/v0.2.0
    cnrm.cloud.google.com/delete-contents-on-destroy: "false" # kpt-set: ${delete-contents-on-destroy}
spec:
  defaultTableExpirationMs: 3600000 # kpt-set: ${default-table-expiration-ms}
  description: "BigQuery audit logs for folder" # kpt-set: ${dataset-description}
  friendlyName: audit-logs # kpt-set: ${dataset-name}
  location: US # kpt-set: ${dataset-location}
---
# BQ Folder Create
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
  kind: Folder
  metadata:
    annotations:
      cnrm.cloud.google.com/organization-id: org-id
    name: logginglogsink-dep-folder # kpt-set: ${log-folder-name}
  spec:
    displayName: Config Connector Folder Sink Sample