apiVersion: v1
kind: ConfigMap
metadata:
  name: bqexportmaria1
data:
  projects-namespace: dbteam1
  dataset-description: BigQuery audit logs for folder
  dataset-location: US
  dataset-name: audit-logs
  default-table-expiration-ms: "3600000"
  delete-contents-on-destroy: "false"
  filter: ""
  log-folder-name: logginglogsink-dep-folder
  platform-project-id: kasna-test-landingzone
  org-id: "923715671876"
