apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: computeinstance-backend # {"$kpt-set":"network"}
  namespace: config-control # {"$kpt-set":"namespace"}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false