# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: https://source.developers.google.com/p/kasna-test-landingzone/r/deployment-repo
    branch: "master"
    dir: "/config"
    auth: gcenode
  sourceFormat: unstructured
