# root-sync.yaml
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    auth: gcenode
    branch: master
    dir: "/config"
    repo: https://source.developers.google.com/p/management-project-id/r/deployment-repo # kpt-set: https://source.developers.google.com/p/${management-project-id}/r/${deployment-repo}
  sourceFormat: unstructured
