apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: sqladmin.googleapis.com
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
      cnrm.cloud.google.com/deletion-policy: "abandon"
      cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/kasna-test-landingzone # kpt-set: projects/${management-project-id}
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqlinstance-name # kpt-set: ${name}
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro
