apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: sqladmin
  namespace: dbteam-1 # {"$kpt-set":"namespace"}
  annotations:
    cnrm.cloud.google.com/disable-on-destroy: "false"
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
spec:
  resourceID: sqladmin.googleapis.com
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: danny-sql-p02 # kpt-set: ${project-id}-${name}
  namespace: dbteam-1 # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro
