apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mari-sql-1u1 # kpt-set: ${project-id}-${name}
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro