apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: blueprints-project-redis-bucket # kpt-set: ${platform-project-id}-${name}
  projects-namespace: config-control # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/platform-project-id: blueprints-project # kpt-set: ${platform-project-id}
spec:
  storageClass: standard # kpt-set: ${storage-class}
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
