apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: blueprints-project-redis-bucket # kpt-set: ${platform-project-id}-${name}
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/disable-on-destroy: "false"
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  resourceID: redis.googleapis.com
---
apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: blueprints-project-redis-bucket # kpt-set: ${platform-project-id}-${name}
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  authorizedNetworkRef:
    external: projects/blueprints-project/global/networks/default # kpt-set: projects/${platform-project-id}/global/networks/${network}
  displayName: blueprints-project-redis-bucket # kpt-set: ${platform-project-id}-${name}
  memorySizeGb: 3
  region: us-central1 # kpt-set: ${region}
  tier: BASIC
