apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-rb-111
data:
  name: maria-redis-bucket-1
  namespace: dbteam-1
  network: default
  project-id: kasna-test-landingzone
  region: us-central1
  storage-class: standard
