apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: firestore.googleapis.com
  namespace: config-controller-system # {"$kpt-set":"namespace"}
---
apiVersion: firestore.cnrm.cloud.google.com/v1beta1
kind: FirestoreIndex
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
  name: firestoreindex-1
  namespace: config-controller-system # {"$kpt-set":"namespace"}
spec:
  collection: sample-collection
  fields:
  - fieldPath: field1
    order: ASCENDING
  - fieldPath: field2
    order: DESCENDING
  queryScope: COLLECTION