apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
data:
  cluster-name: example-us-west4
  environment: dev
  location: us-east4
  master-ip-range: 10.254.0.0/28
  network-name: default
  network-project-id: network-project-id
  networking-namespace: networking
  platform-namespace: config-control
  platform-project-id: platform-project-id
  projects-namespace: projects
  security-group: gke-security-group@example.com
