apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
data:
  group-billing-admins: test_lz_billing@test.kasna.com.au
  group-org-admins: test_lz_dev@test.kasna.com.au
  management-namespace: config-control
  management-project-id: kasna-test-landingzone
  org-id: "923715671876"
