apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: service-account-solution # {"$ref":"#/definitions/io.k8s.cli.setters.service-account-name"}
  namespace: config-controller-system
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-service-account
  namespace: config-controller-system
spec:
  member: user:${IAM_MEMBER?} # {"$ref":"#/definitions/io.k8s.cli.setters.iam-member"}
  role: roles/iam.serviceAccountKeyAdmin # {"$ref":"#/definitions/io.k8s.cli.setters.role"}
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: service-account-solution # {"$ref":"#/definitions/io.k8s.cli.setters.service-account-name"}
