apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: logging.googleapis.com
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: logginglogsink-sample-project # kpt-set: ${name}
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  destination:
    pubSubTopicRef:
      name: kasna-test-landingzone
  filter: resource.type="bigquery_project" AND logName:"cloudaudit.googleapis.com"
  projectRef:
    name: kasna-test-landingzone # kpt-set: ${project-id}
  uniqueWriterIdentity: true
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: logginglogsink-dep-project
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: logginglogsink-dep-project
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/organization-id: "923715671876"
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  name: Project Sink Sample
  billingAccountRef:
    external: 014244-F1A39A-218EB5
