apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: computeinstance-sample-cloudmachine # kpt-set: ${platform-project-id}-${name}
  projects-namespace: projects # kpt-set: ${projects-namespace}
  labels:
    created-from: "image"
    network-type: "subnetwork"
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  bootDisk:
    initializeParams:
      type: pd-ssd
      size: 24
      sourceImageRef:
        external: debian-cloud/debian-9
  machineType: n1-standard-1
  minCpuPlatform: "Intel Skylake"
  networkInterface:
    - aliasIpRange:
        - ipCidrRange: /24
          subnetworkRangeName: cloudrange
      subnetworkRef:
        name: computeinstance-dep-cloudmachine
  zone: us-central1-a
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: computeinstance-dep-cloudmachine
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  autoCreateSubnetworks: false
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: computeinstance-dep-cloudmachine
  projects-namespace: projects # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/platform-project-id: platform-project-id # kpt-set: ${platform-project-id}
spec:
  ipCidrRange: 10.2.0.0/16
  networkRef:
    name: computeinstance-dep-cloudmachine
  region: us-central1
  secondaryIpRange:
    - ipCidrRange: 10.3.16.0/20
      rangeName: cloudrange
