apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: firestore.googleapis.com
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
---
apiVersion: firestore.cnrm.cloud.google.com/v1beta1
kind: FirestoreIndex
metadata:
  name: firestoreindex-1 # kpt-set: ${name}
  namespace: config-controller-system # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # kpt-set: ${project-id}
spec:
  collection: sample-collection
  fields:
    - fieldPath: field1
      order: ASCENDING
    - fieldPath: field2
      order: DESCENDING
  queryScope: COLLECTION
