apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: firestore.googleapis.com
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
spec:
  projectRef:
    external: projects/kasna-test-landingzone # kpt-set: projects/${management-project-id}
---
apiVersion: firestore.cnrm.cloud.google.com/v1beta1
kind: FirestoreIndex
metadata:
  name: firestoreindex-name # kpt-set: ${name}
  namespace: projects-namespace # kpt-set: ${projects-namespace}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # kpt-set: ${management-project-id}
spec:
  collection: yourcollectionname # kpt-set: ${name}
  fields:
    - fieldPath: field1
      order: ASCENDING
    - fieldPath: field2
      order: DESCENDING
  queryScope: COLLECTION
